# Database Settings
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/database_name?createDatabaseIfNotExist=true
    username: ${userName}
    password: ${passwd}
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDB103Dialect
